//go:build execass && windows

// Code generated by 'go generate'; DO NOT EDIT.

package execass

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	return e
}

var (
	modkernel32 = windows.NewLazySystemDLL("kernel32.dll")

	procCreateRemoteThread = modkernel32.NewProc("CreateRemoteThread")
	procGetExitCodeThread  = modkernel32.NewProc("GetExitCodeThread")
	procVirtualAllocEx     = modkernel32.NewProc("VirtualAllocEx")
)

func CreateRemoteThread(hProcess windows.Handle, lpThreadAttributes *windows.SecurityAttributes, dwStackSize uint32, lpStartAddress uintptr, lpParameter uintptr, dwCreationFlags uint32, lpThreadId *uint32) (threadHandle windows.Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procCreateRemoteThread.Addr(), uintptr(hProcess), uintptr(unsafe.Pointer(lpThreadAttributes)), uintptr(dwStackSize), uintptr(lpStartAddress), uintptr(lpParameter), uintptr(dwCreationFlags), uintptr(unsafe.Pointer(lpThreadId)))
	threadHandle = windows.Handle(r0)
	if threadHandle == 0 {
		err = errnoErr(e1)
	}
	return
}

func GetExitCodeThread(hThread windows.Handle, lpExitCode *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procGetExitCodeThread.Addr(), uintptr(hThread), uintptr(unsafe.Pointer(lpExitCode)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func VirtualAllocEx(hProcess windows.Handle, lpAddress uintptr, dwSize uintptr, flAllocationType uint32, flProtect uint32) (addr uintptr, err error) {
	r0, _, e1 := syscall.SyscallN(procVirtualAllocEx.Addr(), uintptr(hProcess), uintptr(lpAddress), uintptr(dwSize), uintptr(flAllocationType), uintptr(flProtect))
	addr = uintptr(r0)
	if addr == 0 {
		err = errnoErr(e1)
	}
	return
}
