[package]
name = "svc"
version = "0.1.0"
edition = "2021"

[dependencies]
russh = { version = "0.63", default-features = false, features = ["ring", "rsa"] }
russh-sftp = "3.0.1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "sync", "macros", "io-util", "process", "fs"] }
sha2 = "0.10"
async-trait = "0.1"
rand = "0.10"
conpty = { version = "0.7", optional = true }
env_logger = { version = "0.11", optional = true }
tokio-rustls = { version = "0.26.6", default-features = false }
rustls = { version = "0.23.45", default-features = false, features = ["ring"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
conpty = "0.7"

[features]
default = []
debug-log = ["dep:env_logger"]
pscan = []
execass = []

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[patch.crates-io]
russh = { path = "vendor/r" }
russh-cryptovec = { path = "vendor/c" }
russh-sftp = { path = "vendor/s" }
russh-util = { path = "vendor/u" }
